version: '3.8'

services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ti2
      POSTGRES_PASSWORD: ti2
      POSTGRES_DB: ti2
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - default

networks:
  default:
    driver: bridge

volumes:
  postgres_data:
